name: Zip Files

on:
  push:
    branches:
    - main

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      # create intranda package
      - name: Use corporate design from intranda and zip it
        run: zip -r obsidian-intranda.zip .obsidian -x .obsidian/plugins/obsidian-better-export-pdf/data-*.json
                
      # create SDE package
      - name: Use corporate design from SDE 
        run: mv .obsidian/plugins/obsidian-better-export-pdf/data-sde.json .obsidian/plugins/obsidian-better-export-pdf/data.json
      - name: create SDE zip
        run: zip -r obsidian-sde.zip .obsidian -x .obsidian/plugins/obsidian-better-export-pdf/data-*.json

      # create neutral package
      - name: Use no specific corporate design 
        run: mv .obsidian/plugins/obsidian-better-export-pdf/data-neutral.json .obsidian/plugins/obsidian-better-export-pdf/data.json
      - name: create neutral zip
        run: zip -r obsidian-neutral.zip .obsidian -x .obsidian/plugins/obsidian-better-export-pdf/data-*.json
      
      # create tag and release
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d %H:%M:%S %Z')" >> $GITHUB_OUTPUT
      - name: Create tag name from date
        id: tagdate
        run: echo "tagdate=$(date +'%Y-%m-%d_%H-%M-%S_%Z')" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tagdate.outputs.tagdate }}
          release_name: ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false

      # upload intranda design 
      - name: Upload intranda
        id: upload-intranda
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: obsidian-intranda.zip
          asset_name: obsidian-intranda.zip
          asset_content_type: application/zip
      
      # upload SDE design   
      - name: Upload SDE
        id: upload-SDE
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: obsidian-sde.zip
          asset_name: obsidian-sde.zip
          asset_content_type: application/zip
          
      # upload neutral design    
      - name: Upload neutral
        id: upload-neutral
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: obsidian-neutral.zip
          asset_name: obsidian-neutral.zip
          asset_content_type: application/zip
      
